// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6wRXB4jut1KKP7pbQdo5yfy34UWmHJg',
    appId: '1:777626255432:web:314e001dd097f0e063587d',
    messagingSenderId: '777626255432',
    projectId: 'moodi-flutter',
    authDomain: 'moodi-flutter.firebaseapp.com',
    storageBucket: 'moodi-flutter.firebasestorage.app',
    measurementId: 'G-Y0V746BZQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSnMDMVlSdf2xG_0Z-haveuM6xE_pVK9E',
    appId: '1:777626255432:android:7c2d50054970a7d563587d',
    messagingSenderId: '777626255432',
    projectId: 'moodi-flutter',
    storageBucket: 'moodi-flutter.firebasestorage.app',
  );
}
